### ISSUE TITLE
Next generation of the Job Execution Module

### ISSUE THREAD

**Issue by tgianos** [Netflix/genie#101]
Possible ideas:

1. move joblauncher code into java code as much as possible.
2. zookeeper for leader selection for job janitor?
3. monitoring thread should be replaced?
4. Thread should wake up and do what it needs to do then go back to sleep or not even exist. Better to be woken up by outside event thread managed by Spring.
5. Consolidate all threads into single thread to save on conflicts and

**Comment by amitsharma1981** [comment]
The joblauncher.sh has hard coded logic that copies Hadoop Configuration files into the current job conf directory. Once we move this functionality to Java we can also move the copy logic in the Yarn Job Manager where it makes more sense.

**Comment by tgianos** [comment]
Constrain job resources on client machines should also be considered to control proceses from spinning out of control.

**Comment by tgianos** [comment]
Possible desired features:

* Ability to scale up and scale down
* Decouple the web code from the job execution code
* Make the execution code reusable as both standalone JAR and receiving messages as a daemon
* Pluggable message accepting and sending
* Leader election for cleanup threads (consolidate threads to one)
* Job thread pool
* Can rerun jobs
* Run client processes as user to protect other system resources
* Authn/Authz support (see other github issue)
* Move code out of bash into something more manageable / testable
* Shared job results directory
