### ISSUE TITLE
Genie configurations for Spark and hadoop upgrade on EMR 

### ISSUE THREAD

**Issue by kraj007** [Netflix/genie#1018]
Hello team,
This is not particularly any issue to report, but we need few suggestions to consider while upgrading stack while integration Genie with airflow.
 we are currently migration to EMR version 6.0.0 which has - amazon hadoop 3.2.1, spark2.4.4 and hive 3.1.2 
our old stack is on EMR 5.23.0 , where we have hadoop -Amazon 2.8.5, Hive 2.3.4 and Spark 2.4.0 , genie version -3.0.1

Need inputs on which version of genie and python client nflx-genie-client , we should use for new stack and what are the configurations setting particularly we should follow for upgrade.

**Comment by tgianos** [comment]
Hi @kraj007. Your Genie is version is quite old. If you want to move to the latest truly stable it would be `3.3.21` however we're running the `4.0.0-rc` versions internally at Netflix. We haven't officially open sourced them quite yet as we work out issues and have to get around to documenting some of the changes. You could try out the [demo](https://netflix.github.io/genie/docs/4.0.0-rc.66/demo/) for example of how it's setup. It also uses the latest python client for interacting with the Genie server.

**Comment by kraj007** [comment]
Thanks @tgianos  we will be using python3.7 for our new stack. If we upgrade to 3.3.21 version , will it work well with latest python client ?
Also can we use genie 3.0.1 with latest python client ?

**Comment by tgianos** [comment]
@kraj007 The demo client uses [Python 3.8](https://github.com/Netflix/genie/blob/master/genie-demo/src/main/docker/client/Dockerfile#L1) with pygenie `3.6.16` so 3.7 should be fine with that version as well.

The REST API hasn't changed drastically between versions so you should be fine. We're only supporting `4.x` and any major bugs found on `3.3.x` at this time. I wouldn't recommend sticking at `3.0.1` if it can be avoided.

**Comment by yanxiaole** [comment]
Hi @tgianos ,
Are Netflix running the same `4.0.0-rc` as GitHub master branch? or does Netflix maintain an internal version?

**Comment by mprimi** [comment]
@yanxiaole we are running RCs releases internally.
However it's still in active development, hence the 'candidate' status. We're making occasionally breaking changes and we need to overhaul documentation before officially releasing 4.0.0. But we're getting close.
