### ISSUE TITLE
Ping on Fast JSON API

### ISSUE THREAD

**Issue by seanfcarroll** [Netflix/genie#1046]
https://github.com/Netflix/fast_jsonapi/pull/474

Would it possible for someone from Netflix to add a notice to this repo pointing to the fork - there are a lot of resources on the internet pointing to the Netflix repo.

If this PR is merged that will cover it.

Thank you Netflix!!

**Comment by mprimi** [comment]
I pinged some people, but that's about all i can do.

**Comment by seanfcarroll** [comment]
Thank you @mprimi
