### ISSUE TITLE
Database cleanup task deleting Active jobs which pass the retention days

### ISSUE THREAD

**Issue by ramakrishnayes** [Netflix/genie#1066]
We recently upgraded our Genie cluster from 3.1.x to 3.3.20.

We use Genie service to submit spark batch jobs as well as spark streaming jobs.
The streaming jobs run for days and months if there is no need to stop explicitly for maintenance  and upgrades.

Issue: in recent versions it seems the Database cleanup task is deleting all the jobs if their creation date is older than the configured retention days. This includes the jobs which are still active and running.

Questions:
Is it intentional to delete all jobs irrespective of status?
Why is the job creation date is used instead of completion date?

**Comment by tgianos** [comment]
@ramakrishnayes this does look like a bug that has been fixed in `4.0.x` during complete rework of persistence tier. I put in a quick attempt at fix for 3.3.x. Take a look at #1067 as it may also address some of your issues with #1065

**Comment by ramakrishnayes** [comment]
@tgianos Great news. Thank you.

**Comment by tgianos** [comment]
@ramakrishnayes please test with `3.3.22` and let us know if these can all be closed.

**Comment by ramakrishnayes** [comment]
@tgianos , sure will do.
