### ISSUE TITLE
Genie 4 Documentation issue : dead link

### ISSUE THREAD

**Issue by Rustem** [Netflix/genie#1121]
Source Page: https://netflix.github.io/genie/docs/4.0.2/reference/#_concepts
* Under section 7.2 Data model there is a link `Genie 3 data model`. When i follow this link it shows me  404 error.
* Dead link address: https://netflix.github.io/genie/concepts/3/DataModel.html

**Comment by tgianos** [comment]
Thanks for heads up, not sure when they get lost but the newer Data Model section https://netflix.github.io/genie/docs/4.0.2/reference/#_data_model covers everything you should need to know anyway. I'll probably remove the link.

**Comment by tgianos** [comment]
It should link here https://netflix.github.io/genie/concepts/2/DataModel.html
