### ISSUE TITLE
User can access job output via API

### ISSUE THREAD

**Issue by tgianos** [Netflix/genie#119]
Currently access for Genie stdout is limited to making HTTP requests to the job output directory. It has been requested that a user can programmatically access this output via API in the Genie client.

**Comment by liviutudor** [comment]
Ideally the `ExecutionClient` will offer a `getJobOutput` which would return a stream that parses the CSV on the fly and returns the fields.

**Comment by tgianos** [comment]
part of #163 and #162 

Should leverage work done in #183

**Comment by amitsharma1981** [comment]
fixed in 3.0.
