### ISSUE TITLE
System periodically runs a monitor process on each node to check health/status of all jobs run on the node

### ISSUE THREAD

**Issue by amitsharma1981** [Netflix/genie#171]
Each node in the Genie cluster periodically starts a Monitor process which checks the health/status of jobs running on the node. This process relies on the existence of the pid of the job to check if its running. If the pid does not exist it assumes that the process is done and look for the return code in the genie.done file. If it cannot find the genie.done file or the return code in it, it marks the job as failed. If it finds the return code, it updates the job status appropriately.

**Comment by tgianos** [comment]
Handled by #189 and #190
