### ISSUE TITLE
Generate Report(s) for Code Coverage

### ISSUE THREAD

**Issue by liviutudor** [Netflix/genie#173]
I noticed we do not employ something like cobertura to analyze unit test coverage and keep the tests to above a certain level to ensure better code quality.
Is this something we are interested in pursuing?

**Comment by tgianos** [comment]
Hey @liviutudor,

As we discussed offline today we have the jococo plugin enabled on the project for test coverage reports. As we move forward in 3.0 we'll have the new CI builds generate coverage reports using that.

Thanks,
Tom

**Comment by tgianos** [comment]
@liviutudor I've enabled Travis CI builds for Genie. Not yet fully implemented as it doesn't deploy the binaries to bintray but I did integrate it with codecov to publish our coverage statistics.

You can see where it is right now on a per branch basis here: https://codecov.io/github/Netflix/genie.

Also codecov has a browser plugin that will overlay the coverage graphs right on top of github files when viewing them. Pretty nice. I'll be adding a "badge" for the coverage once we're further along with Genie 3 and have more tests implemented so the coverage is better.

Will continue to add tests as we go. Closing this issue as complete as the reports are generated and available now.

**Comment by tgianos** [comment]
Going to use this as a generic issue to cover all test related commits
