### ISSUE TITLE
JobClient.waitForCompletion throws ambiguous InterruptedException

### ISSUE THREAD

**Issue by kilink** [Netflix/genie#230]
[JobClient.waitForCompletion](
https://github.com/Netflix/genie/blob/ebff61569f3c17e62db09f73500ce058146ed483/genie-client/src/main/java/com/netflix/genie/client/JobClient.java#L354) throws InterruptedException when the call times out, but the call to [Thread.sleep](https://github.com/Netflix/genie/blob/ebff61569f3c17e62db09f73500ce058146ed483/genie-client/src/main/java/com/netflix/genie/client/JobClient.java#L376) may also throw InterruptedException, making it impossible to distinguish a timeout from a thread interrupt. To properly handle an a legitimate InterruptedException, typically a thread will exit, or set the interrupt flag and propagate the exception up the stack. That's not what I want to do for a timeout.

See [Future.get](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/Future.html#get-long-java.util.concurrent.TimeUnit-) for an example of a method that distinguishes between a timeout and an interrupt.

**Comment by amitsharma1981** [comment]
fixed in 3.0.
