### ISSUE TITLE
Job progress

### ISSUE THREAD

**Issue by vgmartinez** [Netflix/genie#486]
Hi guys,
I planning to use Genie in prod, but i need some functionalities...for example:
It is possible to have somehow the progress of the job in yarn...

https://hadoop.apache.org/docs/stable/hadoop-yarn/hadoop-yarn-site/ResourceManagerRest.html#Cluster_Application_State_API

Thks

**Comment by tgianos** [comment]
Hi @vgmartinez,

This is a logical request and something we've thought about in the past. The reason it isn't implemented is that Genie is intended to be as agnostic of the clusters and engine technologies it's working with as possible. This gives it the greatest flexibility to adapt as these technologies change quickly (just look at how things have moved from MapReduce to other processing engines in the last couple years). If we were to write a bunch of code to parse job logs for Genie jobs to determine what the actual YARN application ID was and then query the cluster for status etc it would be a lot of code tightly coupled to YARN which we don't want to do.

A better long term solution is likely for us to open call back API's that allow jobs to post their own status back to Genie for Genie to report to uses. This way each individual technology can implement it in whatever way is best for them. For example you could envision using Aspects on top of the Spark or Hive client to hook into the points they're getting their own status and report that to Genie. This way Genie would remain agnostic of the underlying technologies but still present downstream users with more information.

We haven't implemented this yet but could explore prioritizing it if there is desire. PR's are always welcome!

Hopefully that helps you out. Let us know if you have other questions.

**Comment by vgmartinez** [comment]
Hi @tgianos,
It make sense, is much better to be agnostic, by now we can survive without this...;) until we think a better way to do this. BTW i have one more question...;)
- We are planning use genie for implement something similar to spark as a service running in EMR, because we need run multiples jobs at the same time. We gonna have 1500 or 2000 jobs by day and using the EMR Steps is imposible to do this. Genie would be a critical part of our application. Do you think it's a good use for genie?

Thanks for the explanation.

**Comment by tgianos** [comment]
If by Spark as a service you have Genie running the Spark client processes against your EMR yarn cluster I think that's perfectly reasonable. We use it for that purpose today alongside all our other engine types (pig, presto, hive, etc)

If you're running Spark SQL you'll have to take advantage of the Genie memory features to make sure the Spark driver is getting enough memory.

We currently run between 40k and 50k jobs per day on our Genie cluster so 1500 to 2000 should be fine. It's designed to scale.

**Comment by vgmartinez** [comment]
Thanks @tgianos...we are in touch.
