### ISSUE TITLE
docker-compose.yml in demo is not working for 3.0.6

### ISSUE THREAD

**Issue by ronhash10** [Netflix/genie#508]
The reason is that genie-demo-apache does not have a public 3.0.6 tag in the docker hub.
Changing the composer to use 3.0.5 composes fine.

**Comment by tgianos** [comment]
Thanks @ronhash10. We were aware of this as the release build for 3.0.6 was done too early and it failed at the docker container build stage before it was caught (and the binaries were already released so we couldn't redo it). We'll be pushing 3.0.7 once we get a few more bug fixes in that should resolve this.

**Comment by tgianos** [comment]
3.0.7 is being released now and build should work to fix the demo.
