### ISSUE TITLE
setsid: failed to execute [...]/run: Text file busy

### ISSUE THREAD

**Issue by jelez** [Netflix/genie#548]
genie-app-3.0.8.jar

We get multiple of those issues:
```
setsid: failed to execute /opt/genie/tmp/jobs/644c2420-602b-11e7-b9b8-06e23ce966f0/run: Text file busy
```
Is this related to this: https://bugs.openjdk.java.net/browse/JDK-8068370

**Comment by mprimi** [comment]
Given that this is an OpenJDK bug, and Genie isn't doing anything wrong per se, aee you suggesting we should implement a workaround for the bug?

Either way, thanks for reporting, this could be useful to others bumping into the same.

**Comment by jelez** [comment]
Hello there is a note in that link: "Update2: a comment in ProcessImpl_md.c says: "Files are created FD_CLOEXEC in Java.", but in fact they are not. Adding O_CLOEXEC to the open flags resolves the issue. Now, need to understand what would be a drawback of adding this flag to every open() call."

https://bugs.openjdk.java.net/browse/JDK-8068370?focusedCommentId=13927223&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13927223

**Comment by jelez** [comment]
Hello, we currently experience around 2% failed jobs due to this error we see is "Failed to load done file." but when we drill down in the logs the source of the error is the setsid: failed... 
Don't you experience this?

**Comment by mprimi** [comment]
As far as I know we haven't had any report of this error (which makes sense as we are not affected by this OpenJDK bug).
It does make sense that a failure to launch results in a failure to load the done file and therefore results in a failed job.

**Comment by mprimi** [comment]
@jelez we recently started to be affected by this bug.
This PR contains a workaround mitigation: https://github.com/Netflix/genie/pull/925
Launching the job as `bash run` rather than directly executing `run` seems to reliably work.
