### ISSUE TITLE
System can log actual exception in logging messages

### ISSUE THREAD

**Issue by amitsharma1981** [Netflix/genie#55]
In certain places in the code genie does not log the actual exception but just the error message. One example is in the HadoopJobManager.java

} catch (IOException e) {
                    String msg = "Unable to copy attachment correctly: " + attachment.getName();
                    logger.error(msg);
                    throw new CloudServiceException(
                            HttpURLConnection.HTTP_INTERNAL_ERROR, msg);
                }

**Comment by tgianos** [comment]
No longer relevant.
