### ISSUE TITLE
Documentation/demo of how to use

### ISSUE THREAD

**Issue by darrenhaken** [Netflix/genie#561]
Are you able to steer me into the documentation of how this works?
The docs page on the Genie website didn't bring anything back.

I've been looking at writing an abstraction like Genie (great minds think alike) so I'm trying to understand if I'm reinventing the wheel and contributing to Genie instead is the right way to go.

Trying to avoid reinventing the wheel ^_^

**Comment by mprimi** [comment]
Hello Darren, I'm guessing you didn't notice the link at the top of the project page: https://netflix.github.io/genie, then go into a specific release to see more details, demo app, API, etc.

**Comment by darrenhaken** [comment]
Hey @mprimi, thanks for sharing and that's exactly what I was looking for. I hadn't delved into the releases to look for the documentation so we can chalk that down to user error :)

Are you currently accepting any forms of contribution to the project?

**Comment by tgianos** [comment]
@darrenhaken We're certainly open to contributions. Feel free to bring up things you're looking to add so we can make sure they make sense for the project before you go and develop and the PR gets rejected

**Comment by darrenhaken** [comment]
@tgianos sounds good I'll keep that in mind as we evaluate the product.

One last thing to ask before I close the ticket, can Genie be used to launch EMR clusters?
I'm aware Netflix do use EMR so I imagine it's been incorporated into the tool.

**Comment by tgianos** [comment]
@darrenhaken Genie does not launch clusters. It's a separation of concerns. Genie stores the metadata about a given cluster. We don't want it to be involved in the cluster lifecycle rather defer to tools specifically designed for handling that which hook into genie to register and de-register clusters.

See [here.](https://netflix.github.io/genie/docs/3.0.9/reference/#_clusters)

**Comment by darrenhaken** [comment]
Great the clusters section really clears that up.

I assumed that Genie was also abstracting the Python tools and Amazon API's which are mentioned in the docs.

This looks really useful so I appreciate you taking the time to explain it 👍

**Comment by darrenhaken** [comment]
Will close the issue off now I've got what I need!
