### ISSUE TITLE
Investigate Server Side Job Queues for Genie

### ISSUE THREAD

**Issue by amitsharma1981** [Netflix/genie#57]
Currently when genie is near capacity it auto-scales to max possible and then starts rejecting jobs, with the onus being on the clients to implement retries, throttling, queues etc. We need to investigate if it makes sense to have this feature on the server side in genie. There are potential issues in this case like getting DDOS'ed etc, so this might be tricky but worth thinking about.

**Comment by tgianos** [comment]
For now we're not going to do this due to concern it could lead to replication of existing job management frameworks like yarn which already do that job well.
