### ISSUE TITLE
Beginner question: how does genie connect to a cluster?

### ISSUE THREAD

**Issue by PeteW** [Netflix/genie#812]
I'm trying to understand something around authentication, specifically how genie initiates the conversation with a "cluster" when its time to run a job. 

I presume that at the time of job invocation, genie can copy application/job scripts/files to the cluster. It can run optional application installation/setup and issue a "command" from within a directory of a machine in the cluster. 

I'm a beginner in genie and EMR, but my experience with workflow tools such as oozie or luigi we might  leverage SSH as a means of caller/worker communication. And that would require credentials and a specific target machine in the cluster. I couldnt find (so far) any related information, anticipating this would be part of the cluster data model. I need to better understand how genie was intended to "talk" to a target cluster or even a specific machine in that cluster possibly, and how to configure a cluster accordingly.

Thank you for what is clearly a wonderfully well-designed architecture.

**Comment by tgianos** [comment]
hey @PeteW. Sorry for delayed response as most of us have been disconnected over the holidays.

In Genie 3.x your assumption is correct the job (client process) runs on the node where the API request lands (provided the node has enough memory capacity to handle the job). In a Genie cluster the node the job is running on will be saved in the database so it can be located later.

**Comment by zuston** [comment]
How genie achieves unified access to data within a job without distinguishing between clusters. According to my understanding, only when the job program does not distinguish between clusters to access data, can genie automatically help users migrate the running cluster of computing tasks, especially when a certain cluster goes offline
