### ISSUE TITLE
User can view linkages between entities in Genie UI

### ISSUE THREAD

**Issue by tgianos** [Netflix/genie#94]
Currently there is no way in the UI to see what commands are linked to a cluster or what application is linked to a command. Since this is such a core design feature it should exist in the UI.

**Comment by amitsharma1981** [comment]
User can view linkages between entities
* Frontpage bug ... Row Shifts
Display a list of UP clusters with jobs running on them
Remove "search" keywod in Titles
Add ability to search Jobs by commands
Tabulate the Results Page with Sort Options
Make the UI completely Read-Only
Add ability to Drill Down for Clusters. The details should list all commands which are links to the cluster.
Differentiate between multiple installations e.g. Prod/Test

**Comment by tgianos** [comment]
This list you put in here @amitsharma1981 we should brea up into individual issues so it's easier to track what has changed when a release goes out
